# Generated by Django 5.2 on 2025-04-10 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockedVisitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("company", models.CharField(max_length=100)),
                ("reason", models.TextField()),
                (
                    "blocked_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("employee_id", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("photo", models.TextField(blank=True, null=True)),
                (
                    "company",
                    models.CharField(
                        choices=[
                            ("Wyzmindz", "Wyzmindz"),
                            ("Transscon", "Transscon"),
                            ("Asteya Services", "Asteya Services"),
                            ("YOCOYA Technologies", "YOCOYA Technologies"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("Work", "Work"),
                            ("Interview", "Interview"),
                            ("Meeting", "Meeting"),
                            ("Appointment", "Appointment"),
                            ("Delivery", "Delivery"),
                            ("Service", "Service"),
                            ("Others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                ("employee_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "person_to_meet",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("host_phone", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "host_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "check_in_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                ("scheduled_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("blocked", "Blocked"),
                            ("checked_out", "Checked Out"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("otp", models.CharField(blank=True, max_length=6, null=True)),
                ("otp_verified", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-check_in_time"],
            },
        ),
    ]
