# Generated by Django 5.2 on 2025-04-10 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visitor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitor",
            name="otp",
        ),
        migrations.RemoveField(
            model_name="visitor",
            name="otp_verified",
        ),
    ]
