# Generated by Django 5.2 on 2025-04-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitor", "0002_remove_visitor_otp_remove_visitor_otp_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="host_approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("scheduled", "Scheduled Later"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="visitor",
            name="host_comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visitor",
            name="scheduled_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
